

services:
  app:
    volumes: &appvolumes
      - ./src/nginx.conf.sample:/var/www/html/nginx.conf:cached
      - ./src:/var/www/html:cached
      - ./env/php-xdebug.ini:/usr/local/etc/php/conf.d/php-xdebug.ini

  phpfpm:
    volumes: *appvolumes
    environment:
      PHP_IDE_CONFIG: "serverName=Firestore"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    env_file: env/db.env
    ports:
      - "8080:80"
    depends_on:
      - db
