<?php
/**
* Purpletree_Marketplace FieldstoShow
* NOTICE OF LICENSE
*
* This source file is subject to the Purpletree License that is bundled with this package in the file license.txt.
* It is also available through online at this URL: https://www.purpletreesoftware.com/license.html
*
* @category    Purpletree
* @package     Purpletree_Marketplace
* @author      Purpletree Software
* @copyright   Copyright (c) 2017
* @license     https://www.purpletreesoftware.com/license.html
*/

$string = '<input type="hidden" name="'.$this->getNamePrefix().'" value="" >
<ul class="checkboxes">';
    foreach ($this->getValues() as $name => $label):
        $check = '';
		if($this->getIsChecked($name)) {
			$check = "checked=checked";
		}
        $string .= '<li>
            <input type="checkbox" value="'.$name.'" name="'.$this->getNamePrefix().'[]" id="'.$this->getHtmlId() . '_' . $name.'" '.$check.'/><label for="'.$this->getHtmlId() . '_' . $name.'">'.$label.'</label></li>';
    endforeach;
    $string .= '</ul>';
    ?>
<?= /* @noEscape */ $string ?>
